In [ ]:
import numpy as np

## Comparing performance with lists, etc.

In [ ]:
N=1000000

In [ ]:
%%time
list_ = list(range(N))
for i in range(N):
    list_[i] = list_[i] * list_[i]

In [ ]:
%%time
list_ = list(range(N))
list_ = [item * item for item in list_]

CPU times: user 11.7 s, sys: 4.56 s, total: 16.2 s
Wall time: 16.2 s


In [ ]:
%%time
list_ = list(range(N))
list_ = map(lambda x: x * x, list_)

CPU times: user 2.61 s, sys: 2.06 s, total: 4.67 s
Wall time: 4.64 s


In [ ]:
%%time
list_ = list(range(N))
list_sum = 0
for item in list_:
    list_sum += item

CPU times: user 14 s, sys: 1.79 s, total: 15.8 s
Wall time: 15.8 s


In [ ]:
%%time
list_ = list(range(N))
list_sum = sum(list_)

In [ ]:
%%time
arr = np.arange(N)
arr = arr * arr

In [ ]:
%%time
arr = np.arange(N)
arr_sum = np.sum(arr)

# Creating np Arrays

In [ ]:
arr = np.arange(5)

In [ ]:
print(arr, type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [ ]:
arr = np.array([0.0, 2, 4, 6, 8])

In [ ]:
print(arr, type(arr))

[0. 2. 4. 6. 8.] <class 'numpy.ndarray'>


In [ ]:
arr

array([0., 2., 4., 6., 8.])

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(5,)

In [ ]:
arr.size

5

In [ ]:
arr.itemsize

8

In [ ]:
arr2d = np.array([
                  [1, 2, 3], 
                  [4, 5, 6]
])

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d.ndim

2

In [ ]:
arr2d.shape

(2, 3)

In [ ]:
arr2d.size

6

In [ ]:
arr3d = np.array([
                  [
                   [1, 2, 3],
                   [4, 5, 6]
                  ],
                  [
                   [7, 8, 9], 
                   [10, 11, 12]
                  ]
])

In [ ]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d.shape

(2, 2, 3)

In [ ]:
arr3d.ndim

3

In [ ]:
arr3d.size

12

In [ ]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
1729 * np.ones((2, 3, 4))

array([[[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]],

       [[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]]])

In [ ]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.random.randn(2, 3)

array([[-0.58355562,  2.00839268, -0.00302992],
       [ 1.48400062,  0.37151012, -0.03635112]])

In [ ]:
np.random.rand(2, 3)

array([[0.2504209 , 0.88068174, 0.25801271],
       [0.67906517, 0.25454034, 0.33785021]])

In [ ]:
np.random.rand(10, 1)

array([[0.60729224],
       [0.89717078],
       [0.3386626 ],
       [0.76859716],
       [0.49247679],
       [0.35900869],
       [0.02055296],
       [0.27322291],
       [0.50897597],
       [0.11743569]])

In [ ]:
np.random.randint(0, 100, (2, 3))

array([[78, 22, 17],
       [ 7, 89, 38]])

In [ ]:
np.arange(7, 71, 7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [ ]:
np.linspace(7, 70, 10)

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [ ]:
np.array([True, False, True, True])

array([ True, False,  True,  True])

In [ ]:
str_arr = np.array(['1.4', '2.1', '1.1'])

In [ ]:
arr = np.array(str_arr, dtype='float')

In [ ]:
arr

array([1.4, 2.1, 1.1])

## indexing

In [ ]:
arr3d = np.array([
                  [
                   [1, 2, 3],
                   [4, 5, 6]
                  ],
                  [
                   [7, 8, 9], 
                   [10, 11, 12]
                  ]
])

In [ ]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
arr3d[0, 0, 0]

1

In [ ]:
arr3d[1, 0, 2]

9

In [ ]:
i = 1
j = 0
k = 2
arr3d[i, j, k]

9

In [ ]:
arr3d[1, :, :]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr3d[:, 1, :]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [ ]:
arr3d[:, :, 0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [ ]:
arr3d % 2 == 0

array([[[False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

In [ ]:
arr3d[arr3d % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
arr3d[(arr3d % 2 == 1) & (arr3d > 3)]

array([ 5,  7,  9, 11])

In [ ]:
arr_slice = arr3d[:, :, 0:2]

In [ ]:
print(type(arr_slice))

<class 'numpy.ndarray'>


In [ ]:
arr_slice.ndim

3

In [ ]:
arr_slice.shape

(2, 2, 2)

In [ ]:
arr_slice[0, 0, 1]

2

In [ ]:
arr_slice[0, 0, 0] = 1729

In [ ]:
arr_slice

array([[[1729,    2],
        [   4,    5]],

       [[   7,    8],
        [  10,   11]]])

In [ ]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [ ]:
arr_slice = np.copy(arr3d[:, :, 0:2])

In [ ]:
arr_slice[0, 0, 0] = 1

In [ ]:
arr_slice

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [ ]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [ ]:
arr = np.random.randint(0, 10, (5))

In [ ]:
arr

array([9, 7, 9, 4, 6])

In [ ]:
my_indices = [1, 3, 4]

In [ ]:
arr[my_indices]

array([7, 4, 6])

# Numpy Operations

In [ ]:
arr1 = np.random.rand(3, 4)
arr2 = np.random.rand(3, 4)

In [ ]:
arr1

array([[0.54926505, 0.02893975, 0.45875842, 0.01661079],
       [0.87879388, 0.12961944, 0.87666711, 0.16116939],
       [0.5051439 , 0.66695509, 0.27690086, 0.13140154]])

In [ ]:
arr2

array([[0.31145038, 0.87616136, 0.02613557, 0.35165177],
       [0.87747564, 0.57515974, 0.68396101, 0.0939003 ],
       [0.04683902, 0.23476387, 0.65019035, 0.68421466]])

In [ ]:
arr1 + arr2

array([[0.86071543, 0.90510111, 0.48489399, 0.36826256],
       [1.75626952, 0.70477918, 1.56062813, 0.2550697 ],
       [0.55198292, 0.90171897, 0.9270912 , 0.81561619]])

In [ ]:
arr1 - arr2

array([[ 0.23781467, -0.84722161,  0.43262286, -0.33504097],
       [ 0.00131823, -0.4455403 ,  0.1927061 ,  0.06726909],
       [ 0.45830488,  0.43219122, -0.37328949, -0.55281312]])

In [ ]:
arr1 * arr2

array([[0.17106881, 0.02535589, 0.01198991, 0.00584121],
       [0.77112022, 0.07455188, 0.59960613, 0.01513385],
       [0.02366045, 0.15657696, 0.18003826, 0.08990686]])

In [ ]:
arr1 / arr2

array([[ 1.76357163,  0.03303016, 17.55303066,  0.04723648],
       [ 1.0015023 ,  0.2253625 ,  1.28175012,  1.71638843],
       [10.78468113,  2.84096137,  0.42587661,  0.19204724]])

In [ ]:
np.exp(arr1)

array([[1.73197964, 1.02936258, 1.58210846, 1.01674952],
       [2.40799362, 1.13839507, 2.40287783, 1.17488397],
       [1.65722398, 1.9482959 , 1.31903559, 1.14042561]])

In [ ]:
np.log(np.exp(arr1))

array([[0.54926505, 0.02893975, 0.45875842, 0.01661079],
       [0.87879388, 0.12961944, 0.87666711, 0.16116939],
       [0.5051439 , 0.66695509, 0.27690086, 0.13140154]])

In [ ]:
np.sin(arr1)

array([[0.52206053, 0.02893571, 0.44283525, 0.01661003],
       [0.76996984, 0.12925678, 0.76861105, 0.16047255],
       [0.48393338, 0.61859645, 0.27337588, 0.13102373]])

In [ ]:
np.cos(arr1)

array([[0.85290844, 0.99958127, 0.896603  , 0.99986204],
       [0.63808029, 0.99161116, 0.63971639, 0.9870403 ],
       [0.87510484, 0.78570887, 0.96190729, 0.99137923]])

In [ ]:
np.sqrt(arr1)

array([[0.74112418, 0.17011688, 0.67731708, 0.12888287],
       [0.93744007, 0.360027  , 0.93630503, 0.40145908],
       [0.71073476, 0.81667319, 0.5262137 , 0.3624935 ]])

In [ ]:
arr_inv = 1 / arr1

In [ ]:
arr_inv

array([[ 1.82061465, 34.55454442,  2.17979649, 60.20182176],
       [ 1.13792327,  7.71489221,  1.14068383,  6.20465203],
       [ 1.97963391,  1.49935132,  3.61140087,  7.61026107]])

In [ ]:
arr1 = np.zeros((3, 5))

In [ ]:
arr_inv = 1/arr1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
print(arr_inv)

[[inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]


In [ ]:
np.isinf(arr_inv[0,0])

True

In [ ]:
np.isinf(arr_inv)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# Broadcasting

In [ ]:
arr1 = np.arange(6)

In [ ]:
arr1.shape

(6,)

In [ ]:
arr1

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr1 = arr1.reshape((3, 2))

In [ ]:
arr1.shape

(3, 2)

In [ ]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr2 = np.arange(6).reshape((3, 2))

In [ ]:
arr2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr1 + arr2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [ ]:
arr2[0].reshape((1, 2))


array([[0, 1]])

In [ ]:
arr1 + arr2[0].reshape((1, 2)) # (3, 2) + (1, 2)

array([[0, 2],
       [2, 4],
       [4, 6]])

In [ ]:
arr2[:, 0].reshape((3, 1))

array([[0],
       [2],
       [4]])

In [ ]:
arr1 + arr2[:, 0].reshape((3, 1)) # (3, 2) + (3, 1)

array([[0, 1],
       [4, 5],
       [8, 9]])

In [ ]:
arr1 + 1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr1 = np.arange(24).reshape((2, 3, 4))

In [ ]:
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
arr2 = np.ones((1, 4))

In [ ]:
arr1 + arr2   # (2, 3, 4) + (1, 4)

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]])

In [ ]:
arr1 = np.arange(4)

In [ ]:
arr2 = np.arange(5)

In [ ]:
print(arr1.shape, arr2.shape)

(4,) (5,)


In [ ]:
arr1 + arr2

ValueError: ignored

In [ ]:
arr1.reshape(4, 1)

array([[0],
       [1],
       [2],
       [3]])

In [ ]:
arr1.reshape(4, 1) + arr2  # (4, 1) + (5)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [ ]:
arr = np.random.rand(3, 3)

In [ ]:
arr

array([[0.34623918, 0.14074649, 0.2471035 ],
       [0.82139936, 0.42968499, 0.76271341],
       [0.16353789, 0.85315848, 0.27458889]])

In [ ]:
arr.T

array([[0.34623918, 0.82139936, 0.16353789],
       [0.14074649, 0.42968499, 0.85315848],
       [0.2471035 , 0.76271341, 0.27458889]])

# File handling

In [ ]:
planets_small = np.loadtxt("planets_small.txt")

ValueError: ignored

In [ ]:
planets_small = np.loadtxt("planets_small.txt", 
                           skiprows = 1)

ValueError: ignored

In [ ]:
planets_small = np.loadtxt("planets_small.txt", 
                           skiprows = 1,
                           usecols = (1, 2, 3, 4, 5, 6, 7, 8, 9))

In [ ]:
planets_small

array([[3.3000e-01, 4.8700e+00, 5.9700e+00, 6.4200e-01, 1.8980e+03,
        5.6800e+02, 8.6800e+01, 1.0200e+02, 1.4600e-02],
       [5.7900e+01, 1.0820e+02, 1.4960e+02, 2.2790e+02, 7.7860e+02,
        1.4335e+03, 2.8725e+03, 4.4951e+03, 5.9064e+03],
       [4.2226e+03, 2.8020e+03, 2.4000e+01, 2.4700e+01, 9.9000e+00,
        1.0700e+01, 1.7200e+01, 1.6100e+01, 1.5330e+02]])

In [ ]:
planets_small.shape

(3, 9)

In [ ]:
planets = np.loadtxt("planets.txt", 
                           skiprows = 1,
                           usecols = (1, 2, 3, 4, 5, 6, 7, 8, 9))

ValueError: ignored

In [ ]:
planets = np.genfromtxt("planets.txt", 
                        skip_header=1, 
                        usecols = [1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
planets

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [ ]:
planets.shape

(20, 9)

In [ ]:
np.isnan(planets)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, 

In [ ]:
planets_new = np.nan_to_num(planets, nan=-1)

In [ ]:
planets_new

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [ ]:
np.savetxt('planets_new.txt', planets_new, 
           delimiter=',')


NameError: ignored

In [ ]:
np.savetxt?

In [ ]:
np.save("planets_new", planets_new)

In [ ]:
!ls -lh

total 24K
-rw-r--r-- 1 root root 1.6K Mar 16 14:47 planets_new.npy
-rw-r--r-- 1 root root 4.5K Mar 16 14:46 planets_new.txt
-rw-r--r-- 1 root root  254 Mar 16 14:38 planets_small.txt
-rw-r--r-- 1 root root 1.5K Mar 16 14:42 planets.txt
drwxr-xr-x 1 root root 4.0K Mar  3 18:11 sample_data


In [ ]:
arr1 = np.random.rand(1000, 10)
arr2 = np.random.rand(2000, 5)
arr3 = np.random.rand(20, 10000)

In [ ]:
np.savez("many_arrs", arr1, arr2, arr3)

In [ ]:
!ls -lh

total 1.8M
-rw-r--r-- 1 root root 1.7M Mar 16 14:52 many_arrs.npz
-rw-r--r-- 1 root root 1.6K Mar 16 14:47 planets_new.npy
-rw-r--r-- 1 root root 4.5K Mar 16 14:46 planets_new.txt
-rw-r--r-- 1 root root  254 Mar 16 14:38 planets_small.txt
-rw-r--r-- 1 root root 1.5K Mar 16 14:42 planets.txt
drwxr-xr-x 1 root root 4.0K Mar  3 18:11 sample_data


In [ ]:
arrs = np.load('many_arrs.npz')

In [ ]:
print(type(arrs))

<class 'numpy.lib.npyio.NpzFile'>


In [ ]:
arrs.files

['arr_0', 'arr_1', 'arr_2']

In [ ]:
arrs['arr_0'].shape

(1000, 10)

In [ ]:
np.savez_compressed('many_arrs_compressed', 
                    arr1, arr2, arr3)

In [ ]:
!ls -lh

total 3.3M
-rw-r--r-- 1 root root 1.6M Mar 16 14:54 many_arrs_compressed.npz
-rw-r--r-- 1 root root 1.7M Mar 16 14:52 many_arrs.npz
-rw-r--r-- 1 root root 1.6K Mar 16 14:47 planets_new.npy
-rw-r--r-- 1 root root 4.5K Mar 16 14:46 planets_new.txt
-rw-r--r-- 1 root root  254 Mar 16 14:38 planets_small.txt
-rw-r--r-- 1 root root 1.5K Mar 16 14:42 planets.txt
drwxr-xr-x 1 root root 4.0K Mar  3 18:11 sample_data


In [ ]:
arr1 = np.zeros((10000, 10000))

In [ ]:
np.savez("zeros", arr1)

In [ ]:
np.savez_compressed("zeros_compressed", arr1)

In [ ]:
!ls -lh

total 767M
-rw-r--r-- 1 root root 1.6M Mar 16 14:54 many_arrs_compressed.npz
-rw-r--r-- 1 root root 1.7M Mar 16 14:52 many_arrs.npz
-rw-r--r-- 1 root root 1.6K Mar 16 14:47 planets_new.npy
-rw-r--r-- 1 root root 4.5K Mar 16 14:46 planets_new.txt
-rw-r--r-- 1 root root  254 Mar 16 14:38 planets_small.txt
-rw-r--r-- 1 root root 1.5K Mar 16 14:42 planets.txt
drwxr-xr-x 1 root root 4.0K Mar  3 18:11 sample_data
-rw-r--r-- 1 root root 760K Mar 16 14:56 zeros_compressed.npz
-rw-r--r-- 1 root root 763M Mar 16 14:55 zeros.npz


# Stats with NumPy

In [ ]:
arr = np.random.rand(10000000,)

In [ ]:
np.amin(arr)

0

In [ ]:
np.amin?

In [ ]:
np.amax(arr)

0.9999915329470833

In [ ]:
np.mean(arr)

0.49835265487727426

In [ ]:
np.var(arr)

0.08305664817400735

In [ ]:
np.std(arr)

0.28819550338963884

In [ ]:
np.median(arr)

0.49774252046580314

In [ ]:
np.percentile(arr, 50)

0.49774252046580314

In [ ]:
np.percentile(arr, 10)

0.10024188502450737

In [ ]:
np.percentile(arr, 90)

0.8985023145814922

In [ ]:
%%time
iqr = np.percentile(arr, 75) - np.percentile(arr, 25)

CPU times: user 280 ms, sys: 36 ms, total: 316 ms
Wall time: 319 ms


In [ ]:
print(iqr)

0.49950783658626163


In [ ]:
%%time
quartiles = np.percentile(arr, [25, 75])
iqr = quartiles[1] - quartiles[0]

CPU times: user 210 ms, sys: 0 ns, total: 210 ms
Wall time: 210 ms


In [ ]:
print(quartiles)

[0.24824011 0.74774795]


In [ ]:
print(iqr)

0.49950783658626163


In [ ]:
(arr - np.mean(arr))/np.std(arr)

array([-1.2076022 , -1.01987303,  1.51760917, ..., -0.47830944,
       -0.33409969,  1.14824894])

In [ ]:
np.histogram(arr)

(array([ 999463,  998650, 1000122,  998223, 1000173, 1000919,  998865,
        1000985, 1001600, 1001000]),
 array([8.45622383e-09, 9.99999856e-02, 1.99999963e-01, 2.99999940e-01,
        3.99999917e-01, 4.99999894e-01, 5.99999871e-01, 6.99999849e-01,
        7.99999826e-01, 8.99999803e-01, 9.99999780e-01]))

In [ ]:
np.histogram(arr, bins=5)

(array([1998113, 1998345, 2001092, 1999850, 2002600]),
 array([8.45622383e-09, 1.99999963e-01, 3.99999917e-01, 5.99999871e-01,
        7.99999826e-01, 9.99999780e-01]))

In [ ]:
np.histogram(arr, bins=[0, 0.25, 0.5, 0.75, 1])

(array([2497818, 2498813, 2500099, 2503270]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [ ]:
bins = [0, 0.25, 0.5, 0.75, 1]

In [ ]:
np.digitize(arr, bins)

array([1, 1, 4, ..., 2, 2, 4])

In [ ]:
arr1 = np.random.randint(0, 10, (10))

In [ ]:
arr1

array([2, 8, 8, 2, 6, 0, 8, 2, 7, 9])

In [ ]:
bins = [0, 6, 10]

In [ ]:
np.digitize(arr1, bins)

array([1, 2, 2, 1, 2, 1, 2, 1, 2, 2])

In [ ]:
np.digitize(arr1, bins, right=True)

array([1, 2, 2, 1, 1, 0, 2, 1, 2, 2])

In [ ]:
arr1 = np.random.randint(50, 80, 100) # weight

In [ ]:
arr2 = np.random.randint(150, 185, 100) # heights

In [ ]:
arr3 = np.random.randint(17, 22, 100) # age

In [ ]:
np.concatenate((arr1, arr2, arr3)).shape

(300,)

In [ ]:
np.vstack((arr1, arr2, arr3)).shape

(3, 100)

In [ ]:
arr2d = np.vstack((arr1, arr2, arr3))

In [ ]:
np.amin(arr2d, axis=1)

array([ 50, 150,  17])

In [ ]:
np.amax(arr2d, axis=1)

array([ 79, 184,  21])

In [ ]:
np.mean(arr2d, axis=1)

array([ 64.48, 167.23,  18.96])

# Checking stats rules with numpy

## Mean subracted array has zero mean

In [ ]:
arr = np.random.rand(1000)

In [ ]:
mean = np.mean(arr)

In [ ]:
arr1 = arr - mean

In [ ]:
np.mean(arr1)

-7.105427357601002e-18

## Computing mean with smaller set of values

In [ ]:
arr = np.random.rand(1000)

In [ ]:
for k in range(1, 50):
    arr1 = arr[0:k]
    print(k, np.mean(arr1))

In [ ]:
np.cumsum?

In [ ]:
means = np.cumsum(arr)/np.arange(1,1001)

In [ ]:
means[0:15]

array([0.80334668, 0.47415025, 0.50657624, 0.57224576, 0.6124674 ,
       0.51811314, 0.5048491 , 0.51491554, 0.49235724, 0.54249526,
       0.52085287, 0.48670218, 0.48395448, 0.45357307, 0.48506273])

## Effect of outliers on mean and median

In [ ]:
arr = np.random.randint(1, 100, 100)

In [ ]:
np.mean(arr)

50.09

In [ ]:
np.median(arr)

50.0

In [ ]:
arr = np.append(arr, [1000, 2000])

In [ ]:
arr.shape

(102,)

In [ ]:
np.mean(arr)

78.51960784313725

In [ ]:
np.median(arr)

50.5

## Effect of scaling arrays on mean and median

In [ ]:
arr = np.random.rand(100)

In [ ]:
np.mean(arr)

0.4383130659902099

In [ ]:
np.median(arr)

0.3970390836194846

In [ ]:
arr1 = 2.5 * arr + 0.65

In [ ]:
print(np.mean(2.5 * arr + 0.65), 
      2.5 * np.mean(arr) + 0.65)

1.7457826649755248 1.7457826649755246


In [ ]:
print(np.median(2.5 * arr + 0.65), 
      2.5 * np.median(arr) + 0.65)

1.6425977090487114 1.6425977090487116


In [ ]:
print(np.var(2.5 * arr + 0.65), 
      2.5*2.5*np.var(arr))

0.4164288169548459 0.4164288169548459


In [ ]:
print(np.std(2.5 * arr + 0.65), 
      2.5 * np.std(arr))

0.6453129604733241 0.6453129604733241


In [ ]:
arr1 = np.random.rand(100)
arr2 = np.random.rand(100)

In [ ]:
print( np.mean(0.21 * arr1 - 0.75 * arr2), 
      0.21 * np.mean(arr1) - 0.75 * np.mean(arr2))

-0.29677089842238513 -0.29677089842238513
